site_name: Python Microservices
site_url: https://github.com/python-microservices/pyms
repo_url: https://github.com/python-microservices/pyms
repo_name: python-microservices/pyms
site_author: Alberto Vara

nav:
  - Home: index.md
  - PyMS Package:
    - Home: home.md
    - Installation: installation.md
    - Quickstart: quickstart.md
    - Configuration: configuration.md
    - Microservice class: ms_class.md
    - Services:
      - List of services: services/services.md
      - Routing: services/routing.md
      - Service Discovery: services/services_discovery.md
    - Encrypt/Decrypt Configuration: encrypt_decryt_configuration.md
    - Command line: command_line.md
  - Introduction to microservices:
      - Introduction to microservices (ENG): microservices.md
      - Introduction to microservices (SPA): microservicios.md
  - Tutorials:
      - Index: tutorials/tutorials.md
      - Basic Examples: tutorials/examples.md
      - Create services: tutorials/tutorial_create_services.md
      - Propagate traces: tutorials/tutorial_propagate_traces.md
      - Testing with PyMS: tutorials/tutorial_testing.md
  - Projects:
    - Scaffold:
        - Index: scaffold/index.md
        - Quickstart: scaffold/quickstart.md
        - Configuration: scaffold/configuration.md
        - Run in Docker: scaffold/runindocker.md
        - Run in Kubernetes: scaffold/runinkubernetes.md
    - Template:
        - Index: template/index.md
  - Contributing:
    - Index: contributing/index.md
    - PyMS structure: contributing/structure.md
  - Articles and events:
    - External Links and Articles: links_articles.md
    - HacktoberfestES: hacktoberfest_es_2020.md

markdown_extensions:
- admonition: null
- pymdownx.tasklist: null

theme:
  name: 'material'
  custom_dir: docs/
  features:
      - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
